defaults: &defaults
  working_directory: ~/graphql-auth
  docker:
    - image: circleci/node:11.12.0
    - image: circleci/postgres:10
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: circleci
  environment:
    NODE_ENV: test
    PG_CONNECTION_STRING: postgresql://circleci@localhost:5432/circleci

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "server/package.json" }}
      - run: cd server && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "server/package.json" }}
      - run:
          name: Run tests with JUnit as reporter
          command: cd server && npm run jest
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: server/reports/junit
      - store_artifacts:
          path: server/reports/junit

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
